### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by DimaCarpov** [DimaCarpov/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by demonjkk** [comment]
"Крутой Уокер", он же "Одинокий волк", он же "Идущий в огне", он же "Лесной воин", он же "Человек президента" или просто Бог среди людей. Может все, или все может.
